# timescout.ai

from dataclasses import dataclass
from math import isclose

PHI = 1.618033988749895  # coherence threshold
CONSCIOUSNESS_RATE = 5.6  # your locked rate [cite:4]

@dataclass
class NavigatorState:
    env: float
    emo: float
    ment: float
    phys: float
    resistance: float      # R (0–1)
    nav_time: float        # τ_nav, time spent navigating
    depletion_rate: float  # k_eff in your calculator

    @property
    def agency(self) -> float:
        return self.env + self.emo + self.ment + self.phys

    @property
    def mer(self) -> float:
        # MER = (Agency / Resistance) × φ
        r = max(self.resistance, 1e-4)
        return (self.agency / r) * PHI

    @property
    def ea_time(self) -> float:
        # EA(t) = E × A = t; here E is implicit scale of nav_time
        # For now, treat nav_time as the time generated by agency usage.
        return self.nav_time

def coherence_state(mer: float, phi: float = PHI) -> str:
    if mer <= 0:
        return "no_agency: navigator not active"
    if mer > phi:
        return "above_phi: coherent navigation (keep going)"
    if isclose(mer, phi, rel_tol=1e-6, abs_tol=1e-6):
        return "at_phi: critical threshold (minimum viable momentum)"
    return "below_phi: decoherence + fatigue (delegate or rest)"